name: F1 Monitor
on:
  schedule:
    - cron: '*/5 * * * *' # 5분마다 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python main.py
